# The code assumes that this table exists, so don't delete it even if you remove
# all aliases from here.
[aliases]
amend = ["squash"]
b = ["bookmark"]
ci = ["commit"]
unamend = ["unsquash"]

[diff.color-words]
max-inline-alternation = 3
context = 3

[diff.git]
context = 3

[git]
private-commits = "none()"
push-bookmark-prefix = "push-"
push-new-bookmarks = false
sign-on-push = false

[ui]
allow-init-native = false
always-allow-large-revsets = false
color = "auto"
default-description = ""
diff-instructions = true
graph.style = "curved"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
paginate = "auto"
progress-indicator = true
quiet = false
log-word-wrap = false
log-synthetic-elided-nodes = true
conflict-marker-style = "diff"
# signature verification is slow, disable by default
show-cryptographic-signatures = false

[ui.movement]
edit = false

[ui.streampager]
interface = "quit-if-one-page"
wrapping = "anywhere"

[snapshot]
max-new-file-size = "1MiB"
auto-track = "all()"
auto-update-stale = false

# TODO: https://github.com/jj-vcs/jj/issues/3419 - Remove when fully deprecated.
[split]
legacy-bookmark-behavior = false
